# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Ramium"
license = "MIT"
licenselink = "https://github.com/rafed/ramium/blob/master/LICENSE"
description = "A modern hugo theme for awesome blogs"
homepage = "https://github.com/rafed/ramium/"
tags = ["blog", "responsive", "google analytics", "disqus", "chords", "google search", "bulma", "fast", "social media share", "code", "math equations", "seo"]
features = ["chordsheetjs", "admin panel", "social media share", "math equations"]
min_version = "0.57.2"

[author]
  name = "Rafed Muhammad Yasir"
  homepage = "https://rafed.github.io/"
